const char* html_response = 
"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"<style>\n"
".container {\n"
"display: flex;\n"
"width: 100%;\n"
"justify-content: space-between;\n"
"}\n"
".square {\n"
"display: flex;\n"
"justify-content: center;\n"
"align-items: center;\n"
"width: calc(50vw - 10px);\n"
"height: calc(50vw - 10px);\n"
"border: 1px solid black;\n"
"}\n"
".rectangle {\n"
"display: flex;\n"
"justify-content: space-around;\n"
"align-items: center;\n"
"width: 100%;\n"
"height: calc((50vw - 10px) / 4);\n"
"border: 1px solid black;\n"
"}\n"
".vslider, .hslider {\n"
"-webkit-appearance: none;\n"
"width: 90%;\n"
"margin: 0 5%;\n"
"background-color: lightblue;\n"
"}\n"
".rectangle div {\n"
"display: flex;\n"
"align-items: center;\n"
"}\n"
".rectangle label {\n"
"margin-left: 5px;\n"
"}\n"
".hslider {\n"
"height: 2em;\n"
"}\n"
".vslider {\n"
"height: 2em;\n"
"transform: rotate(-90deg);\n"
"}\n"
"</style>\n"
"<title>PicoW Rover2</title>\n"
"</head>\n"
"<body>\n"
"<div class=\"rectangle\">\n"
"<label for=\"enable\">Enable:</label>\n"
"<input type=\"checkbox\" id=\"enable\" name=\"enable\" onchange=\"sendEnable(this.checked)\"><br>\n"
"</div>\n"
"\n"
"<div class=\"container\">\n"
"<div id=\"container1\" class=\"square\">\n"
"<input id=\"rangeValue1\" type=\"range\" min=0 max=100  step=1 value=\"50\"\n"
"onmouseup=\"this.value=50; sendValue(this.value, 'hs')\"\n"
"ontouchend=\"this.value=50; sendValue(this.value, 'hs')\"\n"
"oninput=\"sendValue(this.value, 'hs')\" class=\"hslider\">\n"
"</div>\n"
"\n"
"<div id=\"container2\" class=\"square\">\n"
"<input id=\"rangeValue2\" type=\"range\" min=0 max=100  step=1 value=\"50\"\n"
"onmouseup=\"this.value=50; sendValue(this.value, 'vs')\"\n"
"ontouchend=\"this.value=50; sendValue(this.value, 'vs')\"\n"
"oninput=\"sendValue(this.value, 'vs')\" class=\"vslider\">\n"
"</div>\n"
"</div>\n"
"\n"
"<script>\n"
"function sendValue(val, slider) {\n"
"fetch('/', {\n"
"method: 'POST',\n"
"body: slider + '=' + val\n"
"});\n"
"}\n"
"function sendEnable(checked) {\n"
"fetch('/', {\n"
"method: 'POST',\n"
"body: 'en=' + checked\n"
"});\n"
"}\n"
"function heartbeat() {\n"
"fetch('/', {\n"
"method: 'POST',\n"
"body: 'hb'\n"
"});\n"
"setTimeout(heartbeat, 2000);\n"
"}\n"
"heartbeat();\n"
"</script>\n"
"</body>\n"
"</html>\n"
;
